### ISSUE TITLE
TextField Updates

### ISSUE THREAD

**Issue by panvourtsis** [Orfium/orfium-ictinus#55]
- [x] Introduce the new states in TextField (filled - outlined - elevated) ( Issue: #78 )
- [x] Add a new style when focused ( Issue: #78 )
- [ ] Support a smaller input size based on design ( Issue: #126 )
- [ ] TextField prop to define start or end decorator - icon or text 

Error Handling ( Issue: #73 )
- [x] New indicators for success and error of the fields
- [x] Add error message component
- [x] On Error label colour must change as well

New Decorators ( Issue: #77 )
- [ ] Add decorators in TextField (see **with parameters** column in designs)
- [ ] Update color of left icon on error

Multiline Support
- [ ] Add multiline support on text field
- [ ] Support both single line as simple multiline text field and
- [ ] double line that would be with a floating label

**States**
filled - outlined - elevated
Design can be found [here](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/e8803d0d-0c59-4eeb-9d4e-1cae0df12a08/commits/latest/files/d7b356b2-3f84-47de-8d32-8b811b5c4590/layers/9FFE5B59-098C-47A1-B457-14FE07A845B8?collectionId=ed3a1a60-78e2-4d01-a8bd-fd4e8d6356cd&collectionLayerId=672046ce-c06c-4677-bd2a-3dc5f27bdcc6)
simple - left icon - right - indicator - icon and indicator

**TextField component**
Design can be found [here](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/e8803d0d-0c59-4eeb-9d4e-1cae0df12a08/commits/latest/files/d7b356b2-3f84-47de-8d32-8b811b5c4590/layers/0C8A2CB3-97AA-4191-8D8E-8865D27A6C4F?collectionId=ed3a1a60-78e2-4d01-a8bd-fd4e8d6356cd&collectionLayerId=4b90e2b3-7e5d-400a-94fb-d6595af34221)

**TextField error handling**
Design can be found [here](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/e8803d0d-0c59-4eeb-9d4e-1cae0df12a08/commits/latest/files/d7b356b2-3f84-47de-8d32-8b811b5c4590/layers/0C8A2CB3-97AA-4191-8D8E-8865D27A6C4F?collectionId=ed3a1a60-78e2-4d01-a8bd-fd4e8d6356cd&collectionLayerId=4b90e2b3-7e5d-400a-94fb-d6595af34221)

**TextField decorators**
Design can be found [here](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/e8803d0d-0c59-4eeb-9d4e-1cae0df12a08/commits/latest/files/d7b356b2-3f84-47de-8d32-8b811b5c4590/layers/0C8A2CB3-97AA-4191-8D8E-8865D27A6C4F?collectionId=ed3a1a60-78e2-4d01-a8bd-fd4e8d6356cd&collectionLayerId=4b90e2b3-7e5d-400a-94fb-d6595af34221)

**TextField Multiline**
Design can be found [here](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/e8803d0d-0c59-4eeb-9d4e-1cae0df12a08/commits/latest/files/d7b356b2-3f84-47de-8d32-8b811b5c4590/layers/C8B57FD7-3FD4-4DA5-AAF5-1D51933679F8?collectionId=ed3a1a60-78e2-4d01-a8bd-fd4e8d6356cd&collectionLayerId=c2f5351c-f3df-44b0-9774-fab544a47dae)

**Comment by panvourtsis** [comment]
these have been done in `next` version
